Restaurant Management C# DotNet MVC/Final Project/Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using DataLayer.Models;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;

namespace Final_Project.Controllers
{
    public class BillingController : Controller
    {
        DataContext db = new DataContext();
        double subtotals = 0;
        double vat = 0;
        double totalPayable = 0;
        public ActionResult Index()
        {
            if (Session["UserType"] == null || Session["UserType"].Equals(" "))
            {
                return Redirect("/Start/Index");
            }
            ViewBag.billList = db.Bills.ToList();
            sumOfSubtotal();
            return View(db.Products.ToList());
        }

        [HttpPost]
        public ActionResult AddToBill(FormCollection collection)
        {
            if (Session["UserType"] == null || Session["UserType"].Equals(" "))
            {
                return Redirect("/Start/Index");
            }

            if (!productIdIsValid(collection["productId"]))
            {
                Response.Write("<script> alert('Product ID not Found..!'); </script>");
                
            }
            else
            {
                if (!quantityIsValid(collection["productQuantity"]))
                {
                    Response.Write("<script> alert('Quantity is Not Valid..!'); </script>");                   
                }
                else
                {
                    Product p = db.Products.Find(Convert.ToInt32(collection["productId"]));
                    Bill b = new Bill();
                    b.ProductName = p.ProductName;
                    b.Price = p.ProductPrice;
                    b.Quantity = collection["productQuantity"];
                    b.Subtotal =
                        Convert.ToString((Convert.ToDouble(p.ProductPrice))*
                                         (Convert.ToInt32(collection["productQuantity"])));
                    db.Bills.Add(b);
                    db.SaveChanges();
                    sumOfSubtotal();
                    ViewBag.billList = db.Bills.ToList();
                }
            }
            sumOfSubtotal();
            ViewBag.billList = db.Bills.ToList();
            return View(db.Products.ToList());
        }

        public ActionResult PrintBill()
        {
            if (Session["UserType"] == null || Session["UserType"].Equals(" "))
            {
                return Redirect("/Start/Index");
            }

            //Response.Write("<script> alert('PrintBill Called') <script>");
            sumOfSubtotal();
            makePdf(ViewBag.total.ToString(),ViewBag.vat.ToString(),ViewBag.payable.ToString());

            //add records To Sales Table
            {
                Sales s = new Sales();
                DateTime dateTime = DateTime.Today;

                foreach (var b in db.Bills.ToList())
                {
                    s.ProductName = b.ProductName;
                    s.Price = b.Price;
                    s.Quantity = b.Quantity;
                    s.Subtotal = b.Subtotal;
                    s.Date = dateTime.ToString("dd/MM/yyyy");
                    s.Time = DateTime.Now.ToString("hh:mm:ss tt");
                    s.Salesman = Session["Username"].ToString();
                    db.Saleses.Add(s);
                    db.SaveChanges();
                }
               
            }


            // clear bill table after printing the bill
            foreach (var data in db.Bills)
            {
                db.Bills.Remove(data);
            }
            db.SaveChanges();
            ViewBag.billList = db.Bills.ToList();
            return View(db.Products.ToList());
        }

        public ActionResult NewBill()
        {
            if (Session["UserType"] == null || Session["UserType"].Equals(" "))
            {
                return Redirect("/Start/Index");
            }

            foreach (var data in db.Bills)
            {
                db.Bills.Remove(data);
            }
            db.SaveChanges();
            sumOfSubtotal();
            ViewBag.billList = db.Bills.ToList();
            return View(db.Products.ToList());
        }

        public Boolean quantityIsValid(string quantity)
        {
            double qty;
            if (double.TryParse(quantity, out qty))
            {
                if (qty > 0)
                {
                    if (qty % 1 == 0)
                        return true;
                    else
                    {
                        return false;
                    }
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return false;
            }
        }

        public Boolean productIdIsValid(string id)
        {
            double qty;
            if (double.TryParse(id, out qty))
            {
                var user = db.Products.Find(Convert.ToInt32(id));
                if (user != null)
                    return true;
                return false;
            }
            else
            {
                return false;
            }
        }

        public ActionResult Delete(int id)
        {
            if (Session["UserType"] == null || Session["UserType"].Equals(" "))
            {
                return Redirect("/Start/Index");
            }

            Bill b = db.Bills.Find(id);
            db.Bills.Remove(b);
            db.SaveChanges();
            ViewBag.billList = db.Bills.ToList();
            sumOfSubtotal();

            return RedirectToAction("Index");
        }

        public void sumOfSubtotal()
        {
            double subtotals = 0;
            double vat = 0;
            double totalPayable = 0;
            foreach (var b in db.Bills.ToList())
            {
                subtotals += Convert.ToDouble(b.Subtotal);
            }
            vat = subtotals*.15;
            totalPayable = vat + subtotals;

            ViewBag.vat = vat;
            ViewBag.total = subtotals;
            ViewBag.payable = totalPayable;
        }

        public void makePdf(string total,string vat,string payable)
        {
            DataTable dt = new DataTable();
            dt.Columns.AddRange(new DataColumn[4] {
                            new DataColumn("Product Name", typeof(string)),
                            new DataColumn("Price", typeof(string)),
                            new DataColumn("Quantity", typeof(string)),
                            new DataColumn("Subtotal", typeof(string))});

            {
                foreach (var p in db.Bills)
                {
                    string name = p.ProductName;
                    string price = p.Price;
                    string qty = p.Quantity;
                    string subtotal = p.Subtotal;

                    dt.Rows.Add(name, price, qty, subtotal);
                }
            }

            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter hw = new HtmlTextWriter(sw))
                {
                    StringBuilder sb = new StringBuilder();

                    //Generate Invoice (Bill) Header.
                    sb.Append("<table width='100%' cellspacing='0' align='center' cellpadding='2'>");
                    sb.Append("<tr><td align='center' style='background-color: #18B5F0' colspan = '2'>ABC Restaurant</td></tr>");
                    sb.Append("<tr><td align='center' style='background-color: #18B5F0' colspan = '2'>Branch: Dhanmondi, Road: 15, House: 5, D-Block</td></tr>");
                    sb.Append("<tr><td align='center' style='background-color: #18B5F0' colspan = '2'>Phone: 0212382, Email: abcrestaurant@gmail.com</td></tr>");

                    sb.Append("<tr><td colspan = '2'></td></tr>");
                    sb.Append("<tr><td colspan = '2'></td></tr>");
                    sb.Append("<tr><td></br><b>Salesman :</b>  " + Session["Username"] + " </b>");
                    //sb.Append(orderNo);
                    sb.Append("</td><td align = 'right'><b>Date: </b>");
                    sb.Append(DateTime.Now);
                    sb.Append(" </td></tr>");

                    sb.Append("<tr><td align='center' style='background-color: #18B5F0' colspan = '2'><b>Products and Details</b></td></tr>");

                    sb.Append("</table>");
                    sb.Append("<br />");
                    sb.Append("<br />");

                    //Generate Invoice (Bill) Items Grid.
                    sb.Append("<table border = '1'>");
                    sb.Append("<tr>");

                    sb.Append("<th style = 'background-color: #D20B0C;color:#000000' align='center'>");
                    sb.Append("Product Name");
                    sb.Append("</th>");
                    sb.Append("<th style = 'background-color: #D20B0C;color:#000000' align='center'>");
                    sb.Append("Product Price");
                    sb.Append("</th>");
                    sb.Append("<th style = 'background-color: #D20B0C;color:#000000' align='center'>");
                    sb.Append("Product Quantity");
                    sb.Append("</th>");
                    sb.Append("<th style = 'background-color: #D20B0C;color:#000000' align='center'>");
                    sb.Append("Subtotal");
                    sb.Append("</th>");

                    sb.Append("</tr>");
                    foreach (DataRow row in dt.Rows)
                    {
                        sb.Append("<tr>");
                        foreach (DataColumn column in dt.Columns)
                        {
                            sb.Append("<td align='center'>");

Restaurant Management C# DotNet MVC/Final Project/Views/Billing/AddToBill.cshtml
@model IEnumerable<DataLayer.Models.Product>

@{
    ViewBag.Title = "Index";
}
<center>
    <h2>Billing</h2>
</center>
<br>
@using (Html.BeginForm("AddToBill", "Billing", FormMethod.Post))
{
    <table border="1">
        <tr>
            <td height="40px" valign="middle" align="center" width="700px">
                Enter Product ID <input id="productId" name="productId" type="text" runat="server" /> &nbsp &nbsp
                Enter Quantity <input id="productQuantity" name="productQuantity" type="text" runat="server" /> &nbsp <input id="Button1" type="submit" value="Add to Bill" runat="server" />
            </td>
        </tr>
    </table>
}
<br>
<table cellspacing="20px" border="5px">
    <tr>
        <th>
            Products
        </th>
        <th>
            Bill
        </th>
    </tr>
    <tr>
        <td valign="top">

            <table border="2">
                <tr>
                    <th>
                        ProductID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Price
                    </th>
                </tr>


                @foreach (var item in Model)
                {
                    <tr>
                        <td width="80px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductID)
                        </td>
                        <td width="200px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductCategory)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductPrice)
                        </td>
                    </tr>
                }

            </table>
        </td>

        <td valign="top">
            <table border="1">
                <tr>

                    <th>
                        Product
                    </th>

                    <th>
                        Price
                    </th>

                    <th>
                        Quantity
                    </th>

                    <th>
                        Subtotal
                    </th>
                    <th>
                        Action
                    </th>


                    @foreach (DataLayer.Models.Bill b in ViewBag.billList)
                    {
                    <tr>
                        <td width="200px" align="center">@b.ProductName</td>
                        <td width="100px" align="center">@b.Price</td>
                        <td width="100px" align="center">@b.Quantity</td>
                        <td width="100px" align="center">@b.Subtotal</td>
                        <td width="100px" align="center">@Html.ActionLink("Delete", "Delete", new { id = b.ID })</td>
                    </tr>
                    }


                    <tr>
                        <td colspan="3"></td>

                        <td colspan="2" align="left" valign="middle" height="70px">

                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total : @ViewBag.total<br />
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Vat : @ViewBag.vat <br />
                            &nbsp;Payable : @ViewBag.payable

                        </td>

                    </tr>
                    <tr>
                        <td colspan="6" valign="center" align="center" height="50px">
                            <input id="Button1" type="button" value="Print Bill" onclick="location.href='@Url.Action("PrintBill", "Billing")'" />
                            <input id="Button2" type="button" value="New Bill" onclick="location.href='@Url.Action("NewBill", "Billing")'" />

                        </td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>

    <h4>Go to</h4>
<ul>
    <li><a href="/Logout/Index">Logout</a></li>
    <li><a href="/Admin/Index">Admin Home</a></li>
    <li><a href="/AccountRequest/Index">Account Requests</a></li>
    <li><a href="/Accounts/Index">Manage Accounts</a></li>
    <li><a href="/Product/Index">Manage Products</a></li>
    <li><a href="/Password/Index">Change Password</a></li>
    <li><a href="/Billing/Index">Billing</a></li>
    <li><a href="/Sales/Index">Sales</a></li>
</ul>

Restaurant Management C# DotNet MVC/Final Project/Views/Billing/Index.cshtml
@model IEnumerable<DataLayer.Models.Product>

@{
    ViewBag.Title = "Index";
}
<center>
    <h2>Billing</h2>
</center>
<br>
@using (Html.BeginForm("AddToBill", "Billing", FormMethod.Post))
{
    <table border="1">
        <tr>
            <td height="40px" valign="middle" align="center" width="700px">
                Enter Product ID <input id="productId" name="productId" type="text" runat="server" /> &nbsp &nbsp
                Enter Quantity <input id="productQuantity" name="productQuantity" type="text" runat="server" /> &nbsp <input id="Button1" type="submit" value="Add to Bill" runat="server" />
            </td>
        </tr>
    </table>
}
<br>
<table cellspacing="20px" border="5px">
    <tr>
        <th>
            Products
        </th>
        <th>
            Bill
        </th>
    </tr>
    <tr>
        <td valign="top">

            <table border="2">
                <tr>
                    <th>
                        ProductID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Price
                    </th>
                </tr>


                @foreach (var item in Model)
                {
                    <tr>
                        <td width="80px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductID)
                        </td>
                        <td width="200px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductCategory)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductPrice)
                        </td>
                    </tr>
                }

            </table>
        </td>

        <td valign="top">
            <table border="1">
                <tr>

                    <th>
                        Product
                    </th>

                    <th>
                        Price
                    </th>

                    <th>
                        Quantity
                    </th>

                    <th>
                        Subtotal
                    </th>
                    <th>
                        Action
                    </th>
                

                    @foreach (DataLayer.Models.Bill b in ViewBag.billList)
                    {
                        <tr>
                        <td width="200px" align="center">@b.ProductName</td>
                        <td width="100px" align="center">@b.Price</td>
                        <td width="100px" align="center">@b.Quantity</td>
                        <td width="100px" align="center">@b.Subtotal</td>
                        <td width="100px" align="center">@Html.ActionLink("Delete", "Delete", new { id = b.ID })</td>
                        </tr>
                    }
                

                <tr>
                    <td colspan="3"></td>

                    <td colspan="2" align="left" valign="middle" height="70px">

                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total : @ViewBag.total<br/>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Vat : @ViewBag.vat <br/>
                        &nbsp;Payable : @ViewBag.payable

                    </td>

                </tr>
                <tr>
                    <td colspan="6" valign="center" align="center" height="50px">
                        <input id="Button1" type="button" value="Print Bill" onclick="location.href='@Url.Action("PrintBill", "Billing")'" />
                        <input id="Button2" type="button" value="New Bill" onclick="location.href='@Url.Action("NewBill", "Billing")'" />

                    </td>
                </tr>

            </table>
        </td>
    </tr>
</table>

<h4>Go to</h4>
<ul>
    <li><a href="/Logout/Index">Logout</a></li>
    <li><a href="/Admin/Index">Admin Home</a></li>
    <li><a href="/AccountRequest/Index">Account Requests</a></li>
    <li><a href="/Accounts/Index">Manage Accounts</a></li>
    <li><a href="/Product/Index">Manage Products</a></li>
    <li><a href="/Password/Index">Change Password</a></li>
    <li><a href="/Billing/Index">Billing</a></li>
    <li><a href="/Sales/Index">Sales</a></li>
</ul>

Restaurant Management C# DotNet MVC/Final Project/Views/Billing/NewBill.cshtml
@model IEnumerable<DataLayer.Models.Product>

@{
    ViewBag.Title = "Index";
}
<center>
    <h2>Billing</h2>
</center>
<br>
@using (Html.BeginForm("AddToBill", "Billing", FormMethod.Post))
{
    <table border="1">
        <tr>
            <td height="40px" valign="middle" align="center" width="700px">
                Enter Product ID <input id="productId" name="productId" type="text" runat="server" /> &nbsp &nbsp
                Enter Quantity <input id="productQuantity" name="productQuantity" type="text" runat="server" /> &nbsp <input id="Button1" type="submit" value="Add to Bill" runat="server" />
            </td>
        </tr>
    </table>
}
<br>
<table cellspacing="20px" border="5px">
    <tr>
        <th>
            Products
        </th>
        <th>
            Bill
        </th>
    </tr>
    <tr>
        <td valign="top">

            <table border="2">
                <tr>
                    <th>
                        ProductID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Price
                    </th>
                </tr>


                @foreach (var item in Model)
                {
                    <tr>
                        <td width="80px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductID)
                        </td>
                        <td width="200px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductCategory)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductPrice)
                        </td>
                    </tr>
                }

            </table>
        </td>

        <td valign="top">
            <table border="1">
                <tr>

                    <th>
                        Product
                    </th>

                    <th>
                        Price
                    </th>

                    <th>
                        Quantity
                    </th>

                    <th>
                        Subtotal
                    </th>
                    <th>
                        Action
                    </th>


                    @foreach (DataLayer.Models.Bill b in ViewBag.billList)
                    {
                    <tr>
                        <td width="200px" align="center">@b.ProductName</td>
                        <td width="100px" align="center">@b.Price</td>
                        <td width="100px" align="center">@b.Quantity</td>
                        <td width="100px" align="center">@b.Subtotal</td>
                        <td width="100px" align="center">@Html.ActionLink("Delete", "Delete", new { id = b.ID })</td>
                    </tr>
                    }


                    <tr>
                        <td colspan="3"></td>

                        <td colspan="2" align="left" valign="middle" height="70px">

                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total : @ViewBag.total<br />
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Vat : @ViewBag.vat <br />
                            &nbsp;Payable : @ViewBag.payable

                        </td>

                    </tr>
                    <tr>
                        <td colspan="6" valign="center" align="center" height="50px">
                            <input id="Button1" type="button" value="Print Bill" onclick="location.href='@Url.Action("PrintBill", "Billing")'" />
                            <input id="Button2" type="button" value="New Bill" onclick="location.href='@Url.Action("NewBill", "Billing")'" />

                        </td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>

    <h4>Go to</h4>
<ul>
    <li><a href="/Logout/Index">Logout</a></li>
    <li><a href="/Admin/Index">Admin Home</a></li>
    <li><a href="/AccountRequest/Index">Account Requests</a></li>
    <li><a href="/Accounts/Index">Manage Accounts</a></li>
    <li><a href="/Product/Index">Manage Products</a></li>
    <li><a href="/Password/Index">Change Password</a></li>
    <li><a href="/Billing/Index">Billing</a></li>
    <li><a href="/Sales/Index">Sales</a></li>
</ul>

Restaurant Management C# DotNet MVC/Final Project/Views/Billing/PrintBill.cshtml
@model IEnumerable<DataLayer.Models.Product>

@{
    ViewBag.Title = "Index";
}
<center>
    <h2>Billing</h2>
</center>
<br>
@using (Html.BeginForm("AddToBill", "Billing", FormMethod.Post))
{
    <table border="1">
        <tr>
            <td height="40px" valign="middle" align="center" width="700px">
                Enter Product ID <input id="productId" name="productId" type="text" runat="server" /> &nbsp &nbsp
                Enter Quantity <input id="productQuantity" name="productQuantity" type="text" runat="server" /> &nbsp <input id="Button1" type="submit" value="Add to Bill" runat="server" />
            </td>
        </tr>
    </table>
}
<br>
<table cellspacing="20px" border="5px">
    <tr>
        <th>
            Products
        </th>
        <th>
            Bill
        </th>
    </tr>
    <tr>
        <td valign="top">

            <table border="2">
                <tr>
                    <th>
                        ProductID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Price
                    </th>
                </tr>


                @foreach (var item in Model)
                {
                    <tr>
                        <td width="80px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductID)
                        </td>
                        <td width="200px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductCategory)
                        </td>
                        <td width="130px" align="center">
                            @Html.DisplayFor(modelItem => item.ProductPrice)
                        </td>
                    </tr>
                }

            </table>
        </td>

        <td valign="top">
            <table border="1">
                <tr>

                    <th>
                        Product
                    </th>

                    <th>
                        Price
                    </th>

                    <th>
                        Quantity
                    </th>

                    <th>
                        Subtotal
                    </th>
                    <th>
                        Action
                    </th>


                    @foreach (DataLayer.Models.Bill b in ViewBag.billList)
                    {
                    <tr>
                        <td width="200px" align="center">@b.ProductName</td>
                        <td width="100px" align="center">@b.Price</td>
                        <td width="100px" align="center">@b.Quantity</td>
                        <td width="100px" align="center">@b.Subtotal</td>
                        <td width="100px" align="center">@Html.ActionLink("Delete", "Delete", new { id = b.ID })</td>
                    </tr>
                    }


                    <tr>
                        <td colspan="3"></td>

                        <td colspan="2" align="left" valign="middle" height="70px">

                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total : @ViewBag.total<br />
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Vat : @ViewBag.vat <br />
                            &nbsp;Payable : @ViewBag.payable

                        </td>

                    </tr>
                    <tr>
                        <td colspan="6" valign="center" align="center" height="50px">
                            <input id="Button1" type="button" value="Print Bill" onclick="location.href='@Url.Action("PrintBill", "Billing")'" />
                            <input id="Button2" type="button" value="New Bill" onclick="location.href='@Url.Action("NewBill", "Billing")'" />

                        </td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>

    <h4>Go to</h4>
<ul>
    <li><a href="/Logout/Index">Logout</a></li>
    <li><a href="/Admin/Index">Admin Home</a></li>
    <li><a href="/AccountRequest/Index">Account Requests</a></li>
    <li><a href="/Accounts/Index">Manage Accounts</a></li>
    <li><a href="/Product/Index">Manage Products</a></li>
    <li><a href="/Password/Index">Change Password</a></li>
    <li><a href="/Billing/Index">Billing</a></li>
    <li><a href="/Sales/Index">Sales</a></li>
</ul>